name: "Project Deploy"
description: "Deploy a project build"
inputs:
  build_id:
    description: "Build ID to deploy"
    required: false
  deploy_latest_build:
    description: "Deploy the most recent build"
    required: false
    default: false
  project_dir:
    description: "The path to the directory where your hsproject.json file is located"
    required: true
    default: ./
  personal_access_key:
    description: "[SECRET] Personal Access Key, generated in HubSpot, to use the CLI. If not provided, will use DEFAULT_PERSONAL_ACCESS_KEY from environment."
    required: false
    type: string
  account_id:
    description: "HubSpot account ID associated with the personal-access-key. Also known as Portal ID. If not provided, will use DEFAULT_ACCOUNT_ID from environment."
    required: false
    type: number
  cli_version:
    description: "Version of the HubSpot CLI to install. If not provided, will use DEFAULT_CLI_VERSION from environment. If neither are found, defaults to `latest`."
    required: false
    type: string
  profile:
    description: "Profile to use for the HubSpot CLI. If not provided, will use DEFAULT_PROFILE from environment."
    required: false
    type: string
outputs:
  deploy_id:
    description: The deploy ID of the initiated HubSpot project deploy
    value: ${{ steps.deploy-project.outputs.deploy_id }}
runs:
  using: "composite"
  steps:
    - name: Install HubSpot CLI
      uses: HubSpot/hubspot-project-actions/install-hubspot-cli@v1.0.0
      with:
        cli_version: ${{ inputs.cli_version }}
    - name: Deploy a HubSpot project build
      id: deploy-project
      shell: bash
      env:
        HUBSPOT_PERSONAL_ACCESS_KEY: ${{ inputs.personal_access_key || env.DEFAULT_PERSONAL_ACCESS_KEY }}
        HUBSPOT_ACCOUNT_ID: ${{ inputs.account_id || env.DEFAULT_ACCOUNT_ID }}
        HUBSPOT_PROFILE: ${{ inputs.profile || env.DEFAULT_PROFILE }}
      run: |
        # Source shared utilities
        . "$GITHUB_ACTION_PATH/../scripts/action-utils.sh"

        # Validate account and personal access key
        validate_account_and_personal_access_key

        # Resolve and validate project directory
        resolve_project_dir "${{ inputs.project_dir }}"

        # Validate build ID and deploy latest build
        if [ -z "${{ inputs.build_id }}" ] && [ "${{ inputs.deploy_latest_build }}" = "false" ]; then
          echo "Error: build_id or deploy_latest_build is required but neither was set"
          exit 1
        elif [ -n "${{ inputs.build_id }}" ] && [ "${{ inputs.deploy_latest_build }}" = "true" ]; then
          echo "Error: build_id and deploy_latest_build cannot be used together"
          exit 1
        fi

        # Handle profile usage
        PROFILE_ARG=""
        if [ -n "$HUBSPOT_PROFILE" ]; then
          PROFILE_ARG="--profile $HUBSPOT_PROFILE"
        fi

        # Handle deploy latest build usage
        if [ "${{ inputs.deploy_latest_build }}" = "true" ]; then
          BUILD_ARG="--deploy-latest-build"
        else
          BUILD_ARG="--build ${{ inputs.build_id }}"
        fi

        # Run deploy command
        run_hs_command \
          "hs project deploy --use-env --json $BUILD_ARG $PROFILE_ARG" \
          "true"

        # Parse and set outputs
        set_output_from_json "deploy_id" ".deployId"

        echo "✅ Project deployment initiated successfully"
