name: "Project upload"
description: "Upload and build a HubSpot project in your account. If auto-deploy is enabled, the build will also be deployed to your account."
inputs:
  project_dir:
    description: "The path to the directory where your hsproject.json file is located"
    required: true
    default: ./
    type: string
  personal_access_key:
    description: "[SECRET] Personal Access Key generated in HubSpot that grants access to the CLI."
    required: true
    type: string
  account_id:
    description: "HubSpot account ID associated with the personal-access-key."
    required: true
    type: number
outputs:
  build_id:
    description: "The build ID of the created HubSpot project build"
  deploy_id:
    description: "The deploy ID if auto-deploy is enabled"
runs:
  using: "composite"
  steps:
    - name: Upload source code to HubSpot Project
      shell: bash
      env:
        HUBSPOT_PERSONAL_ACCESS_KEY: ${{ inputs.personal_access_key }}
        HUBSPOT_ACCOUNT_ID: ${{ inputs.account_id }}
      run: |
        # Source shared utilities
        . "$GITHUB_ACTION_PATH/../scripts/action-utils.sh"

        # Validate account and personal access key
        validate_account_and_personal_access_key "${{ inputs.account_id }}" "${{ inputs.personal_access_key }}"

        # Resolve and validate project directory
        resolve_project_dir "${{ inputs.project_dir }}"

        # Run upload command
        run_hs_command \
          "hs project upload --force-create --use-env --json --message '${{ github.event.head_commit.message || 'Uploaded via HubSpot GitHub Action' }} (${GITHUB_SHA:0:7})'" \
          "true"

        # Parse and set outputs
        set_output_from_json "build_id" ".buildId"
        set_output_from_json "deploy_id" ".deployId" "true"
