name: "Test HubSpot Project"
description: "Test a HubSpot project using our recommended workflow. This action will validate your project, create a test account, upload your project, and then install the OAuth app."
inputs:
  account_config_path:
    description: "The path to the account config file to use for the test account"
    required: true
    type: string
  project_dir:
    description: "The path to the directory where your hsproject.json file is located"
    required: true
    default: ./
    type: string
  personal_access_key:
    description: "[SECRET] Personal Access Key generated in HubSpot that grants access to the CLI. If not provided, will use DEFAULT_PERSONAL_ACCESS_KEY from environment."
    required: false
    type: string
  account_id:
    description: "HubSpot account ID associated with the personal-access-key. If not provided, will use DEFAULT_ACCOUNT_ID from environment."
    required: false
    type: number
  cli_version:
    description: "Version of the HubSpot CLI to install. If not provided, will use DEFAULT_CLI_VERSION from environment. If neither are found, defaults to `latest`."
    required: false
    type: string
outputs:
  test_account_id:
    description: "The account ID of the test account created for the project"
  auth_code:
    description: "The auth code for the installed OAuth app"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: HubSpot Project Validation Action
      uses: ./project-validate
      with:
        project_dir: ${{ inputs.project_dir }}
    - name: HubSpot Test Account Creation Action
      id: test-account-create-step
      uses: ./create-test-account
      with:
        account_config_path: ${{ inputs.account_config_path }}
    - name: HubSpot Project Upload Action
      uses: ./project-upload
      with:
        project_dir: ${{ inputs.project_dir }}
        personal_access_key: ${{ steps.test-account-create-step.outputs.personal_access_key }}
        account_id: ${{ steps.test-account-create-step.outputs.account_id }}
    - name: HubSpot Install OAuth App Action
      uses: ./install-oauth-app
      with:
        test_account_id: ${{ steps.test-account-create-step.outputs.account_id }}
        project_dir: ${{ inputs.project_dir }}
        personal_access_key: ${{ steps.test-account-create-step.outputs.personal_access_key }}
        account_id: ${{ steps.test-account-create-step.outputs.account_id }}
