name: "Install OAuth App"
description: "Install an OAuth app into a Developer Test Account"
inputs:
  test_account_id:
    description: "The account ID of the test account to install your app into"
    required: true
    type: string
  project_dir:
    description: "The path to the directory where your hsproject.json file is located"
    required: true
    default: ./
  personal_access_key:
    description: "[SECRET] Personal Access Key, generated in HubSpot, to use the CLI. If not provided, will use DEFAULT_PERSONAL_ACCESS_KEY from environment."
    required: false
    type: string
  account_id:
    description: "HubSpot account ID associated with the personal-access-key. Also known as Portal ID. If not provided, will use DEFAULT_ACCOUNT_ID from environment."
    required: false
    type: number
  cli_version:
    description: "Version of the HubSpot CLI to install. If not provided, will use DEFAULT_CLI_VERSION from environment. If neither are found, defaults to `latest`."
    required: false
    type: string
outputs:
  auth_code:
    description: The auth code returned by the app install
    value: ${{ steps.install-app.outputs.auth_code }}
runs:
  using: "composite"
  steps:
    - name: Install HubSpot CLI
      uses: ./install-hubspot-cli
      with:
        cli_version: ${{ inputs.cli_version }}
    - name: Install an OAuth app into a Developer Test Account
      id: install-app
      shell: bash
      env:
        HUBSPOT_PERSONAL_ACCESS_KEY: ${{ inputs.personal_access_key || env.DEFAULT_PERSONAL_ACCESS_KEY }}
        HUBSPOT_ACCOUNT_ID: ${{ inputs.account_id || env.DEFAULT_ACCOUNT_ID }}
      run: |
        # Source shared utilities
        . "$GITHUB_ACTION_PATH/../scripts/action-utils.sh"

        # Validate account and personal access key
        validate_account_and_personal_access_key

        # Resolve and validate project directory
        resolve_project_dir "${{ inputs.project_dir }}"

        # Validate test account ID
        if [ -z "${{ inputs.test_account_id }}" ]; then
          echo "Error: test_account_id is required but was not set"
          exit 1
        fi

        # Run app install command
        run_hs_command \
          "hs app install ${{ inputs.test_account_id }} --use-env --network-debug" \
          "true"

        # Parse and set outputs
        set_output_from_json "auth_code" ".authCode"

        echo "✅ App installed successfully"
