name: "Project validate"
description: "Validate the configuration of a HubSpot project"
inputs:
  project_dir:
    description: "The path to the directory where your hsproject.json file is located"
    required: true
    default: ./
    type: string
  personal_access_key:
    description: "[SECRET] Personal Access Key generated in HubSpot that grants access to the CLI."
    required: true
    type: string
  account_id:
    description: "HubSpot account ID associated with the personal-access-key."
    required: true
    type: number
outputs:
  validation_result:
    description: "The validation result of the HubSpot project"
runs:
  using: "composite"
  steps:
    - name: Validate HubSpot project
      shell: bash
      env:
        HUBSPOT_PERSONAL_ACCESS_KEY: ${{ inputs.personal_access_key }}
        HUBSPOT_ACCOUNT_ID: ${{ inputs.account_id }}
      working-directory: ${{ inputs.project_dir }}
      run: |
        hs project validate | jq -r '{"validation_result":.result} | to_entries | .[] | "\(.key)=\(.value)"' >> "$GITHUB_OUTPUT"
