name: "Project validate"
description: "Validate the configuration of a HubSpot project"
inputs:
  project_dir:
    description: "The path to the directory where your hsproject.json file is located"
    required: true
    default: ./
    type: string
  personal_access_key:
    description: "[SECRET] Personal Access Key generated in HubSpot that grants access to the CLI."
    required: true
    type: string
  account_id:
    description: "HubSpot account ID associated with the personal-access-key."
    required: true
    type: number
runs:
  using: "composite"
  steps:
    - name: Validate HubSpot project
      shell: bash
      env:
        HUBSPOT_PERSONAL_ACCESS_KEY: ${{ inputs.personal_access_key }}
        HUBSPOT_ACCOUNT_ID: ${{ inputs.account_id }}
      run: |
        # Convert to absolute path if relative
        if [[ "${{ inputs.project_dir }}" != /* ]]; then
          project_dir="$GITHUB_WORKSPACE/${{ inputs.project_dir }}"
        else
          project_dir="${{ inputs.project_dir }}"
        fi

        if [ ! -d "$project_dir" ]; then
          echo "Error: Project directory not found at path: $project_dir"
          exit 1
        fi

        if [ ! -f "$project_dir/hsproject.json" ]; then
          echo "Error: hsproject.json not found in directory: $project_dir"
          exit 1
        fi

        cd "$project_dir"

        # Run validation - command will exit with non-zero if validation fails
        hs project validate --use-env
