name: "Project Validate"
description: "Validate the configuration of a HubSpot project"
inputs:
  project_dir:
    description: "The path to the directory where your hsproject.json file is located"
    required: true
    default: ./
    type: string
  personal_access_key:
    description: "[SECRET] Personal Access Key generated in HubSpot that grants access to the CLI. If not provided, will use DEFAULT_PERSONAL_ACCESS_KEY from environment."
    required: false
    type: string
  account_id:
    description: "HubSpot account ID associated with the personal-access-key. If not provided, will use DEFAULT_ACCOUNT_ID from environment."
    required: false
    type: number
  cli_version:
    description: "Version of the HubSpot CLI to install. If not provided, will use DEFAULT_CLI_VERSION from environment. If neither are found, defaults to `latest`."
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Install HubSpot CLI
      uses: ./install-hubspot-cli
      with:
        cli_version: ${{ inputs.cli_version }}
    - name: Validate HubSpot project
      shell: bash
      env:
        HUBSPOT_PERSONAL_ACCESS_KEY: ${{ inputs.personal_access_key || env.DEFAULT_PERSONAL_ACCESS_KEY }}
        HUBSPOT_ACCOUNT_ID: ${{ inputs.account_id || env.DEFAULT_ACCOUNT_ID }}
      run: |
        # Source shared utilities
        . "$GITHUB_ACTION_PATH/../scripts/action-utils.sh"

        # Validate account and personal access key
        validate_account_and_personal_access_key

        # Resolve and validate project directory
        resolve_project_dir "${{ inputs.project_dir }}"

        # Run validation - command will exit with non-zero if validation fails
        hs project validate --use-env

        echo "✅ Project validation completed successfully"
