name: "Create Test Account"
description: "Create a new test account from a configuration file"
inputs:
  account_config_path:
    description: "The path to the test account configuration file"
    required: true
    type: string
  personal_access_key:
    description: "[SECRET] Personal Access Key generated in HubSpot that grants access to the CLI."
    required: true
    type: string
  account_id:
    description: "HubSpot account ID associated with the personal-access-key."
    required: true
    type: number
outputs:
  personal_access_key:
    description: "The personal access key of the created test account"
  account_id:
    description: "The account ID of the created test account"
runs:
  using: "composite"
  steps:
    - name: Create new HubSpot test account
      shell: bash
      env:
        HUBSPOT_PERSONAL_ACCESS_KEY: ${{ inputs.personal_access_key }}
        HUBSPOT_ACCOUNT_ID: ${{ inputs.account_id }}
      run: |
        if [ -z "${{ inputs.account_config_path }}" ]; then
          echo "Error: account_config_path is required but was not set"
          exit 1
        fi

        if [ ! -f "${{ inputs.account_config_path }}" ]; then
          echo "Error: Test account config file not found at path: ${{ inputs.account_config_path }}"
          exit 1
        fi

        # Store the command output in a variable
        output=$(hs test-account create --use-env --json --config-path "${{ inputs.account_config_path }}")
        exit_code=$?

        if [ $exit_code -eq 0 ]; then
          echo "$output" | jq -r '{"personal_access_key":.personalAccessKey, "account_id":.accountId} | to_entries | .[] | "\(.key)=\(.value)"' >> "$GITHUB_OUTPUT"
        else
          echo "Error: Failed to create test account. Command output:"
          echo "$output"
          exit $exit_code
        fi
