name: 'Project build'
description: 'Upload and build a HubSpot project'
inputs:
  project_dir:
    description: 'Directory where hsproject.json is'
    required: true
    default: ./
    type: string
  personal-access-key: 
    description: '[SECRET] Personal Access Key, generated in HubSpot, to use the CLI.'
    required: true
    type: string
  account-id: 
    description: 'HubSpot account ID associated with the personal-access-key. Also known as Portal ID.'
    required: true
    type: number

outputs:
  build_id:
    description: 'The build ID of the created HubSpot project build'
runs:
  using: "composite"
  steps:
    - name: Upload source code to HubSpot Project
      shell: bash
      env:
        HUBSPOT_PERSONAL_ACCESS_KEY: ${{ inputs.personal-access-key }}
        HUBSPOT_ACCOUNT_ID: ${{ inputs.account-id }}
      working-directory: ${{ inputs.project_dir }}
      run: |
        hs project upload --force-create --use-env --message "${{ github.sha }}" | grep 'Build' | awk -F "#" '{print $2}' | awk '{print "build_id=" $1}' >> "$GITHUB_OUTPUT"
