on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: HubSpot CLI Install
        uses: ./install-cli
        with:
          cli_version: 7.7.16-experimental.2
      - name: HubSpot Project Upload Action
        uses: ./project-upload
        with:
          account_id: ${{ secrets.HUBSPOT_ACCOUNT_ID }}
          personal_access_key: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}
          project_dir: ./.github/workflows/example-project
