on: [push, workflow_dispatch]

env:
  DEFAULT_PERSONAL_ACCESS_KEY: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}
  DEFAULT_ACCOUNT_ID: ${{ secrets.HUBSPOT_ACCOUNT_ID }}
  DEFAULT_PROFILE: "prod"
  DEFAULT_CLI_VERSION: "7.7.16-experimental.9"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: HubSpot Project Validation Action
        uses: ./project-validate
        with:
          project_dir: ./.github/workflows/example-project
      - name: HubSpot Project Upload Action
        uses: ./project-upload
        with:
          project_dir: ./.github/workflows/example-project
